name: Never Let Go
favicon: null
layout_spectrum: 0.6663643335923553
typography_spectrum: 0.3634161530062556
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6546712724957615
  lightness: 0.7599009843543172
  saturation: 0.6103973123244941
  rhythmicContrast: 0.7236203555949032
purpose: []
